### PR TITLE
Update C1.cpp

### PR DESCRIPTION
**Pull request by aiwosiwo**

### CODE REVIEW

**Comment by Imimpeccable** [comment]
1. Logical error in determining a tie
2. IsWin function has redundant judgments

**Comment by sanders-h** [comment]
syntax:
Variables ‘player1’ and ‘player2’ are unused

**Review by sanders-h — COMMENTED** [review]
syntax:
Variables ‘player1’ and ‘player2’ are unused

**Comment by MioAyanokouji** [comment]
Input/output:
1. No repeated judgment or range judgment on the input
2. Wrong input hints
3. Output of final grid can be simplified

**Pull request closed without merging**
